### ISSUE TITLE
Magisk Alpha su doesn't support -c option

### ISSUE THREAD

**Issue by CECoffee** [agnostic-apollo/sudo#9]
### Environment 
- Magisk version: b1dc47a0-alpha (29001)
- termux-sudo version: 1.2.0

### Details
When I execute `sudo xxx`, it always throws out the following error:
```
~ $ sudo nmap -O 1.1.1.1
No 'su' binary found that supports the '-c', '--shell', '--preserve-environment' and '--mount-master' options
SU_SEARCH_PATHS: /system/bin/su /debug_ramdisk/su /system/xbin/su /sbin/su /sbin/bin/su /system/sbin/su /su/xbin/su /su/bin/su /magisk/.core/bin/su
sudo requires a 'su' binary that supports the '-c', '--shell', '--preserve-environment' and '--mount-master' options
```
Further, I executed `sudo -vv su`:
```
~ $ sudo -vv su

Running sudo

Running sudo_set_su_variables
A su binary found at '/debug_ramdisk/su'
The su binary found does not support '-c' option, continuing search
No 'su' binary found that supports the '-c', '--shell', '--preserve-environment' and '--mount-master' options
SU_SEARCH_PATHS: /system/bin/su /debug_ramdisk/su /system/xbin/su /sbin/su /sbin/bin/su /system/sbin/su /su/xbin/su /su/bin/su /magisk/.core/bin/su
sudo requires a 'su' binary that supports the '-c', '--shell', '--preserve-environment' and '--mount-master' options
```
Obviously, magisk su mounted at `/debug_ramdisk/su` is correctly recognized.
`sudo` says it doesn't receive necessary params like '-c', but it's actually fine if I directly run `/debug_ramdisk/su -c 'ls -a'` in MT terminal:
```
#/ /debug_ramdisk/su -c 'ls -a'
.                          mi_ext
..                         mnt
acct                       odm
apex                       odm_dlkm
bin                        oem
bootstrap-apex             opconfig
bugreports                 opcust
cache                      postinstall
config                     proc
cust                       product
d                          sdcard
data                       second_stage_resources
data_mirror                storage
debug_ramdisk              sys
dev                        system
etc                        system_dlkm
init                       system_ext
init.environ.rc            tmp
init.recovery.hardware.rc  vendor
linkerconfig               vendor_dlkm
metadata
```

**Comment by agnostic-apollo** [comment]
What's the output of `su --help` and `su --version`?

**Comment by CECoffee** [comment]
```
~ $ su --help
MagiskSU

Usage: su [options] [--] [user [argument...]]

Options:
  -s, --shell SHELL             Use SHELL instead of the default /system/bin/sh
  -i, --interactive             Force pseudo-terminal allocation
  -g, --group GROUP             Specify the primary group
  -G, --supp-group GROUP        Specify a supplementary group
                                The first specified supplementary group is also used
                                as a primary group if the option -g is not specified
  -Z, --context CONTEXT         Change SELinux context
  -t, --target PID              PID to take mount namespace from
                                pid 0 means magisk global mount namespace
  -d, --drop-cap                Drop all Linux capabilities
  -m, -p,
  --preserve-environment        Preserve the entire environment
  -v, --version                 Display version number and exit
  -V                            Display version code and exit
  -h, --help                    Display this help message and exit

--: Force stop options parsing, and also stop when an unknown option is found
User: The user to switch to (default root), it can be name or uid
Argument: Pass it to the shell as is

~ $ su --version
b1dc47a0-alpha:MAGISKSU
```

**Comment by agnostic-apollo** [comment]
Where is this line in your build? Install official magisk  and latest build.

https://github.com/topjohnwu/Magisk/blob/b1dc47a047f134f87943eb424309356d22091db5/native/src/core/su/su.cpp#L41

**Comment by CECoffee** [comment]
`su -c` is [deprecated](https://t.me/magiskalpha/681) in Magisk Alpha. [Magisk#9003](https://github.com/topjohnwu/Magisk/issues/9003#issuecomment-2868360246)

**Comment by agnostic-apollo** [comment]
No, you just need to pass `--interactive` along with `-c` for tty allocation, and that was fixed in https://github.com/agnostic-apollo/sudo/commit/746ba74bde8a57811db121c56c638f724f582715

**Comment by CECoffee** [comment]
> When a TTY is required, using su -c is incorrect, as this option is intended for executing non-interactive commands and should not be used to launch a shell.
The -c parameter is merely a legacy compatibility measure: it was designed to indicate the command content to be forwarded to the remote shell. In theory, all remaining arguments should be forwarded to the remote shell, which would then parse -c itself. Unfortunately, due to historical reasons, -c does not provide a TTY.
Therefore, do not use -ic to specify a shell. Instead, use the long-existing -s option.

`su -ic` is a compatibility feature. Instead, use the `-s` option is expected in Magisk Alpha,  which aligns with the behavior of su on Linux.
Though `su -ic` still exists in Magisk, it has been deprecated in Alpha. Hope that `sudo` could adapt to the latter.

**Comment by agnostic-apollo** [comment]
>-s, --shell SHELL Use SHELL instead of the default /system/bin/sh

`-s` is to set shell used, which is already set to `bash` by sudo. `-c` and `-i` are completely different options about passing commands to the shell started, or starting tty. `-c` option is necessary to exist to pass commands and removing it will break 10-15 years of user scripts.

**Comment by CECoffee** [comment]
It's not removed, but is passed and resolved by remote shell, just like shown previously, `/debug_ramdisk/su -c 'ls -a'` executed correctly. [Magisk Pull#9017](https://github.com/topjohnwu/Magisk/pull/9017)

**Comment by agnostic-apollo** [comment]
I see, that should work too, but the `--help` output should still have some reference of `-c`, if even at the end describing this behavior so that clients can match this, even if `su` itself does not handle the option itself anymore. The current `-c, --command` output can also be kept with additional info that this will be handled with the shell set by `--shell`, as otherwise users will also wonder where the `-c` option went. And that it should be passed after other `su` options.

**Comment by CECoffee** [comment]
@vvb2060

**Comment by agnostic-apollo** [comment]
For reference https://github.com/agnostic-apollo/sudo/blob/50b2ec4455b63e3a117d8a1ca7025c3cc8923322/sudo#L836-L838

**Comment by vvb2060** [comment]
https://cs.android.com/android/platform/superproject/+/android-latest-release:system/extras/su/su.cpp

**Comment by agnostic-apollo** [comment]
Yes, I am aware of that, `adb root` `su` is not supported by `sudo` (nor is it normally callable by apps), and that's why those checks exist. And in addition to `-c`, it also doesn't support `--shell`, `--preserve-environment` and `--mount-master`.

- https://github.com/agnostic-apollo/sudo/blob/master/site/pages/en/projects/docs/usage/index.md#su-search-paths

**Comment by vvb2060** [comment]
su should not have -c, that is a feature of sh, not su. Parsing help output is unstable, you should use su -V and -v

**Comment by agnostic-apollo** [comment]
I understand that, but `adb root` `su` still does not support it.

```shell
emu64xa:/ $ /system/xbin/su --help                                                                 
usage: su [WHO [COMMAND...]]

Switch to WHO (default 'root') and run the given COMMAND (default sh).

WHO is a comma-separated list of user, group, and supplementary groups
in that order.

emu64xa:/ $ /system/xbin/su -c ls                                                                  
su: invalid uid/gid '-c'

1|emu64xa:/ $ /system/xbin/su root -c ls                                                           
su: failed to exec -c: No such file or directory
```

> Parsing help output is unstable, you should use su -V and -v

Hasn't failed in years and I can't possibly check every possible random forks of magisk and other su providers exporting their own versions. Checking help output is commonly used in linux to check supported command options. If you don't want to add info about `-c` to help output, especially to help users know how to run commands without running an interactive shell, I can just check `--shell`, but that can still return false positives in other `su` implementations.

**Comment by juandvasquezp** [comment]
Sorry if it's a dumb question, @agnostic-apollo but, the way I gain root access is with adb root through Shizuku's rish.

It doesn't have a --help option but it does have -c and preserves the environment by default. It uses /system/bin/sh and termux path. Do you think it is compatible?

I made a wrapper script faking the --help option and taking everything after -c as a command and everything has been working good so far. But it is in fact adb root at the core. I'm asking just in case I might be missing something.

```
#!/data/data/com.termux/files/usr/bin/bash

RISH="/data/data/com.termux/files/usr/bin/rish"

# Fake help output so that `sudo` accepts this as a valid `su`
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
echo "Usage: su [OPTION]... [-c COMMAND] [args...]"
echo "Options:"
echo "  -c, --command               command to run"
echo "      --shell                 shell to use"
echo "      --preserve-environment preserve environment"
echo "      --mount-master          use mount master"
exit 0
fi

# Parsing to capture the full command after -c
COMMAND=""
COLLECT_CMD=0

for arg in "$@"; do
    if [[ "$arg" == "-c" ]]; then
        COLLECT_CMD=1
        continue
    fi

    if [[ $COLLECT_CMD -eq 1 ]]; then
        # Capture everything after -c as a single full command
        COMMAND="$arg"
        COLLECT_CMD=2
        continue
    fi

    if [[ $COLLECT_CMD -eq 2 ]]; then
        COMMAND="$COMMAND $arg"
    fi
done

# Execute the full command using rish -c
if [ -n "$COMMAND" ]; then
    exec "$RISH" -c "$COMMAND"
else
    exec "$RISH"
fi
```

**Comment by SainoNamkho** [comment]
> I understand that, but `adb root` `su` still does not support it.
> 
> emu64xa:/ $ /system/xbin/su --help                                                                 
> usage: su [WHO [COMMAND...]]
> 
> Switch to WHO (default 'root') and run the given COMMAND (default sh).
> 
> WHO is a comma-separated list of user, group, and supplementary groups
> in that order.
> 
> emu64xa:/ $ /system/xbin/su -c ls                                                                  
> su: invalid uid/gid '-c'
> 
> 1|emu64xa:/ $ /system/xbin/su root -c ls                                                           
> su: failed to exec -c: No such file or directory
> > Parsing help output is unstable, you should use su -V and -v
> 
> Hasn't failed in years and I can't possibly check every possible random forks of magisk and other su providers exporting their own versions. Checking help output is commonly used in linux to check supported command options. If you don't want to add info about `-c` to help output, especially to help users know how to run commands without running an interactive shell, I can just check `--shell`, but that can still return false positives in other `su` implementations.

Regardless of the developer of magisk alpha not recommending `-c`, it does support `-c`. Checking it in the help message is never a reliable way even we ignore magisk alpha.
Add I don't agree with the logic looping through all `su`s for the first one supporting `-c`. Shouldn't `sudo` just forward command to the first `su` found? Additional checkings are incorrect. If the preferred `su` in search path does not support `-c`, errors should not be hidden, it's not what `sudo` supposed to do.

**Comment by agnostic-apollo** [comment]
> Checking it in the help message is never a reliable way even we ignore magisk alpha.

Unix utils often have various implementations provided by GNU, BSD or MACOS, with their own command line options and they being different across multiple versions of same implementation as features get added/removed, it is very common to check help output to check supported options before running commands when writing portable software. And `sudo` has been reliable for many years since it was created, until magisk alpha broke it.

Magisk alpha can simply add

```
-c COMMAND         Pass COMMAND to the invoked shell. The -c option
                   should be the last option as it is not processed by
                   su and must be supported by invoked shell, like it
                   is supported by the default /system/bin/sh shell.
```

> Shouldn't sudo just forward command to the first su found?

`sudo` checks for `-c`, `--shell`, `--preserve-environment` and `--mount-master` options as they are all required for it to function. Not all implementations provide all options, like `adb su` does not have any of those, lineage os `su` didn't used to support `--preserve-environment` and so wasn't supported.  `--shell` is required to pass termux `bash` shell.  `--preserve-environment` is required to preserve to the env exported by Termux app and `sudo` itself so that termux execution env works properly. `--mount-master` is required to setup root home if its in rootfs or system partition as remount would be required. There have many `su` binary implementations and I can't check version names for every one and keep adding names of every fork of each implementation and also keep track of which version added which feature, its not viable, not to mention even magisk alpha or others could remove some other option in future breaking things. Paths alone are obviously not enough, especially first one found, since first one many not support the required options, users have weird configurations often.

- https://github.com/agnostic-apollo/sudo/blob/master/sudo#L836-L851

**Comment by agnostic-apollo** [comment]
@juandvasquezp Sorry missed this, it should probably work, but since you are using `bash`, you should collect all the `-c` args in a bash array instead of a variable as later will break the args, assuming `rish` supports multiple args for `-c`.

**Comment by agnostic-apollo** [comment]
I have opened the #19 pull which should hopefully fix the issue, the test build is attached if someone with magisk alpha, etc can test it before I merge.
